<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net6.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PlanFlow.Core</RootNamespace>
    <AssemblyName>PlanFlow.Core</AssemblyName>
  </PropertyGroup>

</Project>
